version: "3"

vars:
  FUNCTION_APP_NAME: cwa-ws-prod-redirect-func

tasks:
  test:
    dir: function
    cmds:
      - go test ./...

  docker-build:
    dir: function
    cmds:
      - container system start
      - container build -t clowa/az-func-redirect:dev .
    sources:
      - "**/*.go"
    method: checksum

  docker-run:
    dir: function
    deps:
      - docker-build
    cmds:
      - container run -p 8080:8080 clowa/az-func-redirect:dev

  run-locally:
    dir: function
    cmds:
      - docker compose up {{.CLI_ARGS}}
    silent: false

  down:
    dir: function
    cmds:
      - docker compose down
    silent: false

  function-build:
    dir: function
    cmds:
      - rm -rf ./bin
      - CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -o ./bin/main ./src
    silent: false
    sources:
      - "**/*.go"
    method: checksum

  function-deploy:
    deps: [build]
    dir: function
    cmds:
      - func azure functionapp publish {{.FUNCTION_APP_NAME}} --custom
    silent: false
    sources:
      - ./bin/*
      - host.json
      - "**/function.json"
    method: checksum
